sudo: required
services:
  - docker
before_install:
  - docker build -t bobac_image -f Dockerfile.dev .
script:
  - docker run -e CI=true bobac_image npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "my-website"
  env: "MyWebsite-env"
  bucket_name: "elasticbeanstalk-us-east-2-841835679746"
  bucket_path: "my-website"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"